module.id=content-lake-repo-model
module.aliases=content-lake-repo-model
module.title=Content Lake Repo Model
module.description=Alfresco content model for Content Lake scope control
module.version=${project.version}
